;1、域名组
ruleset=🔰 AI1,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
ruleset=🔰 AI2,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI2.list
ruleset=📀 YouTube,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/YouTube.list
ruleset=📀 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🎥 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🎥 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=🎥 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎥 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=👯‍♂️ TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=🔰 AI1`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=🔰 AI2`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=📀 YouTube`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=📀 Spotify`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=🎥 流媒体`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=👯‍♂️ TikTok`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=📘 GitHub`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=🙋 Telegram`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=🌍 国外`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT
custom_proxy_group=➡️ 国内`select`[]DIRECT`[]♻️所有-自动`[]日韩-自动`[]日本-自动`[]韩国-自动`[]美国-自动`[]印度-自动`[]澳大利亚-自动`[]REJECT

;3、节点组
custom_proxy_group=♻️所有-自动`url-test`.*`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=日韩-自动`url-test`(韩|春川|首尔|东京|大阪|日)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=日本-自动`url-test`(东京|大阪|日)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=韩国-自动`url-test`(韩|春川|首尔)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=美国-自动`url-test`(美国|圣尼赛)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=印度-自动`url-test`(印度|孟买|海得拉巴)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=澳大利亚-自动`url-test`(澳大利亚|悉尼)`http://www.gstatic.com/generate_204`180,5,100

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
